services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: first-nest
    ports:
      - 5434:5432
